services:
  db:
    image: postgres:15.2
    secrets:
      - postgrespassword
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgrespassword
    ports:
      - ${POSTGRES_PORT:-5432}
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    depends_on:
      - db
    image: ${WEB_IMAGE:-ghcr.io/marcbey/kanban:latest}
    secrets:
      - databaseurl
      - secretkeybase
    deploy:
      replicas: ${WEB_REPLICAS:-1}
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      DATABASE_URL_FILE: /run/secrets/databaseurl
      SECRET_KEY_BASE_FILE: /run/secrets/secretkeybase
    ports:
      - 4000:4000
    command: >
      bash -c "bin/migrate && bin/server"

volumes:
  db_data:

secrets:
  postgrespassword:
    file: ./secrets/.postgrespassword
  databaseurl:
    file: ./secrets/.databaseurl
  secretkeybase:
    file: ./secrets/.secretkeybase
