name: CI/CD Elixir

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04
    name: Compile with mix test, format, dialyzer & unused deps check
    env:
      MIX_ENV: test

    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1.17.3
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Cache deps directory
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache plt files
        uses: actions/cache@v4
        env: 
          EX_OTP_VERSIONS: ${{ steps.setup-beam.outputs.elixir-version }}
          KEY_BASE: plt-${{ runner.os }}-${{ env.EX_OTP_VERSIONS }}
        with:
          path: |
            priv/plts
          key: |
            ${{ env.KEY_BASE }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ env.KEY_BASE }}-

      - name: Get dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mix deps.get

      - run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test --max-failures 1 --trace --warnings-as-errors

      - name: Check code is formatted
        run: mix format --check-formatted

      - name: Dialyzer static analysis
        run: MIX_ENV=dev mix dialyzer --format github

      - name: Checks unused dependencies
        run: mix deps.unlock --check-unused

  packer-validate:
    runs-on: ubuntu-22.04
    name: Validate Packer configuration
    steps:
      - uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Initialize Packer
        run: cd packer && packer init .

      - name: Validate Packer configuration
        run: cd packer && packer validate -var-file=ci.pkrvars.hcl .

      - name: Check Packer formatting
        run: cd packer && packer fmt -check -diff -recursive .

  build-amd64:
    runs-on: ubuntu-22.04
    needs: ci
    name: Build AMD64 Docker image
    outputs:
      unique_docker_tag: ${{ steps.build-amd64.outputs.sha_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Build and push AMD64 image
        id: build-amd64
        uses: ./.github/actions/build-docker
        with:
          platforms: linux/amd64
          push: true
          cache: true
          gh_pat: ${{ secrets.GH_PAT }}

  build-arm64:
    runs-on: ubuntu-22.04
    needs: ci
    name: Build ARM64 Docker image
    steps:
      - uses: actions/checkout@v4

      - name: Build and push ARM64 image
        uses: ./.github/actions/build-docker
        with:
          platforms: linux/arm64
          push: true
          cache: true
          gh_pat: ${{ secrets.GH_PAT }}

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    needs: build-amd64
    name: Deploy application
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy
        with:
          github_user: ${{ github.repository_owner }}
          gh_pat: ${{ secrets.GH_PAT }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          age_key: ${{ secrets.AGE_KEY }}
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          image_tag: ${{ needs.build-amd64.outputs.unique_docker_tag }}
